apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: 9000       # Port nội bộ Service
      targetPort: 80   # Port của Container (Nginx)
