apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: http
      port: 80          # Cổng của Service (ClusterIP)
      targetPort: 80    # Khớp với containerPort của Nginx trong Deployment
      protocol: TCP
