apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.containerPort }} # Nginx trong container mở cổng 80
          env:
            # 1. Config từ values.yaml
            - name: APP_ENV
              value: {{ .Values.backend.env.APP_ENV | quote }}
            - name: APP_DEBUG
              value: {{ .Values.backend.env.APP_DEBUG | quote }}
            - name: APP_URL
              value: "http://{{ .Values.ingress.host }}"
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            
            # 2. Secret từ K8s (Password, Key)
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_USERNAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: JWT_SECRET
