{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yorisoi-ingress
  annotations:
    # kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" | quote }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      # 1. Backend nhận /api  (Theo yêu cầu của bạn)
      - path: /api 
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-svc
            port: 
              number: {{ .Values.backend.servicePort }}
      # 2. Backend nhận /api (Chuẩn Laravel)
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-svc
            port: 
              number: {{ .Values.backend.servicePort }}
      # 3. Frontend nhận phần còn lại
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}-svc
            port: 
              number: {{ .Values.frontend.servicePort }}
{{- end }}
