# Ghi đè cấu hình của chart cha
yorisoi-stack:
  existingSecret: "yorisoi-secret"
  backend:
    image:
      repository: harbor.local.thongdev.site/lab-final/backend
      tag: "v1.0.0"
    nginxImage:
      repository: harbor.local.thongdev.site/lab-final/nginx-backend
      tag: "v1.0.0"
    env:
      APP_ENV: "local"
      APP_DEBUG: "true"
      # URL local giả lập production
      APP_URL: "http://dr.thongdev.site"
      DB_HOST: "mysql-svc"
      DB_CONNECTION: "mysql"
  frontend:
    image:
      repository: harbor.local.thongdev.site/lab-final/frontend
      tag: "v1.0.0"
    env:
      # Frontend gọi Backend qua /api 
      API_URL: "/api "

  mysql:
    enabled: true  # <--- BẬT MySQL Local
    storageSize: 2Gi
    containerPort: 3306
    servicePort: 3306
    defaultPort: 3306
    backoffLimit: 5
    hostPath: "/data/mysql-pv"
    nodeHostName: k8s-master-2

  ingress:
    host: "dr.thongdev.site"
    className: "nginx"
    enabled: true
